# Generated by Django 3.0.7 on 2021-04-26 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_productattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_value', models.CharField(max_length=45)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('attribute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.ProductAttribute')),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_attribute_value_created_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_attribute_value_modify_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
