# Generated by Django 3.0.7 on 2021-04-26 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_productattributevalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('short_description', models.CharField(blank=True, max_length=100)),
                ('lond_description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('special_price_from', models.DateField(blank=True, null=True)),
                ('special_price_to', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('meta_title', models.CharField(max_length=50, null=True)),
                ('meta_description', models.TextField(null=True)),
                ('meta_keywords', models.TextField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_modify_by', to=settings.AUTH_USER_MODEL)),
                ('product_categories', models.ManyToManyField(to='custom_admin.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.ImageField(null=True, upload_to='uploads/product_images')),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_image_created_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_image_modify_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='custom_admin.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.ProductAttribute')),
                ('product_attribute_value_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custom_admin.ProductAttributeValues')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.Product')),
            ],
        ),
    ]
