# Generated by Django 3.1.5 on 2022-01-11 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_product_productattributeassoc_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('Plate_number', models.CharField(blank=True, max_length=30, verbose_name='plate number')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField()),
                ('created_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Number_created_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Number_modify_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_categories',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='productattributeassoc',
            name='product_attribute_id',
        ),
        migrations.RemoveField(
            model_name='productattributeassoc',
            name='product_attribute_value_id',
        ),
        migrations.RemoveField(
            model_name='productattributeassoc',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productattributevalues',
            name='attribute_name',
        ),
        migrations.RemoveField(
            model_name='productattributevalues',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productattributevalues',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeAssoc',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValues',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
