# Generated by Django 3.1.5 on 2022-01-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_auto_20220111_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberplate',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='numberplate',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='numberplate',
            name='status',
        ),
    ]
