# Generated by Django 3.1.5 on 2022-01-12 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_auto_20220111_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='modify_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='numberplate',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
