# Generated by Django 3.1.5 on 2022-01-12 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_auto_20220112_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='created_by',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='modify_by',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
