# Generated by Django 3.1.5 on 2022-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_auto_20220112_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='modify_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
